config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }

  resources :messages
  resources :rooms

  authenticated :user do
    root to: 'rooms#index', as: :authenticated_root
  end

  root to: redirect('/users/sign_in'), constraints: ->(request) { !request.env['warden'].user }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  after_create_commit { MessageBroadcastJob.perform_later(self) }
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages
  has_many :users, through: :messages
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  validates :name, :email, presence: true
  validates_uniqueness_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /messages or /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1 or /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages or /messages.json
  def create
    @message = Message.new(message_params)
    @message.save
  end

  # PATCH/PUT /messages/1 or /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to message_url(@message), notice: "Message was successfully updated." }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1 or /messages/1.json
  def destroy
    @message.destroy

    respond_to do |format|
      format.html { redirect_to messages_url, notice: "Message was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def message_params
      params.require(:message).permit(:content, :user_id, :room_id)
    end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def home
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /rooms or /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1 or /rooms/1.json
  def show
    @rooms = Room.all
    render 'index'
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms or /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to room_url(@room), notice: "Room was successfully created." }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1 or /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to room_url(@room), notice: "Room was successfully updated." }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1 or /rooms/1.json
  def destroy
    @room.destroy

    respond_to do |format|
      format.html { redirect_to rooms_url, notice: "Room was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.require(:room).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
  </head>

<body data-controller="room" class="<%= yield(:body_class) %>">
<nav class="navbar navbar-expand-lg navbar-light bg-light" role="navigation">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <h1 class="title is-5">Chat World</h1>
    <% end %>
    <button class="navbar-toggler" type="button" id="burger" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <% if user_signed_in? %>
        <%# <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" aria-expanded="false">
            Account
          </a>
          <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <li><%= link_to current_user.name, edit_user_registration_path, class:"dropdown-item" %></li>
            <%# <li><%= button_to "Log Out", destroy_user_session_path, method: :delete, class:"dropdown-item" %></li>
          <%# </ul> %>
        <%# </li>  %>

          <li class="nav-item">
            <%= link_to current_user.name, edit_user_registration_path, class: "nav-link btn btn-warning" %>
          </li>
          <li class="nav-item">
            <%= button_to "Log Out", destroy_user_session_path, method: :delete, class: "nav-link btn btn-warning"%>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign In", new_user_session_path, class: "nav-link btn btn-warning" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign up", new_user_registration_path, class: "nav-link btn btn-warning"%>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>


<%= yield(:header) %>

<div class="container">

  <%= yield %>

</div>

<script>
  document.addEventListener('DOMContentLoaded', function () {
    document.querySelector('#burger').addEventListener('click', function () {
      document.querySelector('#navbarNav').classList.toggle('show');
    });

    // Close dropdowns when clicking outside
    document.addEventListener('click', function (event) {
      var dropdowns = document.querySelectorAll('.dropdown-menu');
      dropdowns.forEach(function (dropdown) {
        if (!dropdown.contains(event.target)) {
          dropdown.classList.remove('show');
        }
      });
    });

    var scrollToElement = document.getElementById('scrollToElement');
    if (scrollToElement) {
      scrollToElement.scrollIntoView({ behavior: 'smooth' });
    }
  });
</script>

</body>
</html>

app/views/messages/_form.html.erb
<%= form_with(model: message) do |form| %>
  <% if message.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
        <% message.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <%= form.hidden_field :user_id, value: current_user.id %>
  <%= form.hidden_field :room_id, value: @room.id %>

  <div class="message-box">
    <div class="input-group">
      <%= form.text_field :content, placeholder: 'Type your message here...', class: 'form-control', label: false, wrapper: false, autocomplete:'off' %>
    </div>
    <div class="input-group-append">
      <%= form.submit "Add Message", class: "btn btn-primary" %>
    </div>
  </div>

<% end %>

app/views/messages/_message.html.erb
<div class="message <%= 'me' if message.user == current_user %>">
  <div class="content-container">
    <div class="message-content" >
      <%= message.content %>
    </div>
    <div class="author">
      <%= message.user.name %> 
    </div>
  </div>
</div>

app/views/messages/_mine.html.erb
<div class="message me">
  <div class="content-container">
    <div class="message-content" >
      <%= message.content %>
    </div>
    <div class="author">
      <%= message.user.name %> 
    </div>
  </div>
</div>

app/views/messages/_theirs.html.erb
<div class="message">
  <div class="content-container">
    <div class="message-content" >
      <%= message.content %>
    </div>
    <div class="author">
      <%= message.user.name %> 
    </div>
  </div>
</div>

app/views/messages/create.js.erb
document.getElementById('message_text_field').value = '';

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render "form", message: @message %>

<br>

<div>
  <%= link_to "Show this message", @message %> |
  <%= link_to "Back to messages", messages_path %>
</div>

app/views/messages/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Messages</h1>

<div id="messages">
  <% @messages.each do |message| %>
    <%= render message %>
    <p>
      <%= link_to "Show this message", message %>
    </p>
  <% end %>
</div>

<%= link_to "New message", new_message_path %>

app/views/messages/new.html.erb
<h1>New message</h1>

<%= render "form", message: @message %>

<br>

<div>
  <%= link_to "Back to messages", messages_path %>
</div>

app/views/messages/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @message %>

<div>
  <%= link_to "Edit this message", edit_message_path(@message) %> |
  <%= link_to "Back to messages", messages_path %>

  <%= button_to "Destroy this message", @message, method: :delete %>
</div>

app/views/page/home.html.erb
<h1>Page#home</h1>
<p>Find me in app/views/page/home.html.erb</p>
<% if current_user %>
  <%= link_to "Logout", destroy_user_session_path , method: :delete %>
<% else%>
  <%= link_to "Login", new_user_session_path %>
<% end %>

<%= content_tag(:div, "", data: {
    controller: 'room'
})%>

app/views/rooms/_form.html.erb
<%= form_with(model: room, local: true) do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
        <% room.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group mb-3">
    <%= form.label "Add a new room" %>
    <%= form.text_field :name, class: 'form-control', placeholder: "Room name", id: "message_text_field" %>
  </div>

  <%= form.submit "Add", class: "btn btn-outline-primary btn-block", id: "add_room_button" %>
<% end %>

app/views/rooms/_room.html.erb
<div id="<%= dom_id room %>">
  <p>
    <strong>Name:</strong>
    <%= room.name %>
  </p>

</div>

app/views/rooms/edit.html.erb
<h1>Editing room</h1>

<%= render "form", room: @room %>

<br>

<div>
  <%= link_to "Show this room", @room %> |
  <%= link_to "Back to rooms", rooms_path %>
</div>

app/views/rooms/index.html.erb
<div id="room-id" data-room-id="<%= @room.try(:id) %>"></div>
<div id="user-id" data-user-id="<%= current_user.id %>"></div>

<div class="container-fluid">
  <div class="row">
  <div class="col-3 rooms-sidebar">
    <p>Hello, <%= current_user.name %> </p>
    <%= render 'form', room: Room.new%>
    <hr/>

    <% @rooms.each do |room| %>
      <%= link_to room, class: 'room-link' do %>
        <% active_class = (@room == room) ? 'active' : '' %>
        <div class="card no-outline mb-2 room-card <%= active_class%>">
            <p class="card-body">
              <span class="name"><%= room.name %><span><br/>
              <span class="member-count"><small><%= room.users.uniq.count %> Members</small></span>
            </p>
        </div>
        <% end %>
    <% end %>
  </div>
  
  <div class="col-9">
    <% if @room.present? %>
      <div class="chat-room">
        <nav class="navbar navbar-light bg-light">
          <b class="navbar-brand" href="#"><%= @room.name %></b><br/>
          <small><%= @room.users.uniq.count %> Members</small>
        </nav>
        <div id="messages">
          <% @room.messages.each_with_index do |message, index| %>
            <div id="<%= index == @room.messages.size - 1 ? 'scrollToElement' : '' %>">
              <%= render 'messages/message', message: message %>
            </div>
          <% end %>
        </div>
        <div class="chat-box">
          <%= render 'messages/form', message: Message.new, room: @room %>
        </div>
      </div>
    <% end %>
  </div>
</div>
</div>

app/views/rooms/new.html.erb
<h1>New room</h1>

<%= render "form", room: @room %>

<br>

<div>
  <%= link_to "Back to rooms", rooms_path %>
</div>

app/views/rooms/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @room %>

<div>
  <%= link_to "Edit this room", edit_room_path(@room) %> |
  <%= link_to "Back to rooms", rooms_path %>

  <%= button_to "Destroy this room", @room, method: :delete %>
</div>